apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: automode
  labels:
    strimzi.io/cluster: appdev-kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824